version: '3.4'

services:
  swtestapp:
    image: swtestapp:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_swtestapp$
    volumes:
      - C:\Users\billy\source\repos\swTestApp\swTestApp:/app
      - C:\Users\billy\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_swtestapp$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_swtestapp$ bin/Debug/netcoreapp2.0/swTestApp.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
